import { css } from "@styled-system/css";

export const styles = {
  passport: css({
    position: "relative",
    w: "100%",
    maxW: { base: "31rem", md: "44rem" },
    h: { base: "clamp(11.25rem, 27svh, 14.5rem)", sm: "18rem", md: "21rem" },
    justifySelf: "center",
    m: "0",
    filter: "drop-shadow(0 24px 34px rgba(59, 47, 47, 0.13))",
  }),
  booklet: css({
    position: "absolute",
    left: { base: "7%", md: "9%" },
    top: { base: "7%", md: "5%" },
    w: { base: "33%", md: "31%" },
    h: "76%",
    display: "grid",
    justifyItems: "center",
    alignContent: "start",
    gap: { base: "2", md: "3" },
    px: { base: "3", md: "5" },
    py: { base: "5", md: "7" },
    overflow: "hidden",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "rgba(232, 93, 117, 0.18)",
    borderRadius: { base: "14px", md: "18px" },
    color: "rgba(161, 112, 41, 0.92)",
    bg: "linear-gradient(145deg, #FADADD, #F6A9B4)",
    boxShadow: "inset 0 0 0 1px rgba(255, 247, 237, 0.28), 0 16px 26px rgba(232, 93, 117, 0.18)",
    transform: "rotate(-5deg)",
    _before: {
      content: "''",
      position: "absolute",
      inset: "6%",
      borderWidth: "1px",
      borderStyle: "dashed",
      borderColor: "rgba(161, 112, 41, 0.3)",
      borderRadius: { base: "10px", md: "14px" },
    },
  }),
  bookletTitle: css({
    position: "relative",
    maxW: "7ch",
    color: "rgba(161, 112, 41, 0.86)",
    fontFamily: "Georgia, 'Times New Roman', serif",
    fontSize: { base: "0.72rem", sm: "0.95rem", md: "1.06rem" },
    fontWeight: "700",
    lineHeight: "1.12",
    letterSpacing: "0",
    textAlign: "center",
    textTransform: "uppercase",
  }),
  bookletPlane: css({
    position: "relative",
    mt: { base: "0", md: "1" },
    transform: "rotate(-26deg)",
  }),
  bookletCake: css({
    position: "relative",
    mt: { base: "1", md: "2" },
  }),
  bookletHeart: css({
    position: "relative",
    mt: "1",
    fill: "currentColor",
  }),
  ticket: css({
    position: "absolute",
    right: { base: "0", md: "2%" },
    bottom: { base: "10%", md: "11%" },
    w: { base: "74%", md: "75%" },
    h: { base: "59%", md: "58%" },
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) 21%",
    overflow: "hidden",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "rgba(161, 112, 41, 0.12)",
    borderRadius: { base: "14px", md: "18px" },
    color: "rgba(161, 112, 41, 0.92)",
    bg: "rgba(255, 247, 237, 0.96)",
    boxShadow: "inset 0 0 0 1px rgba(255, 255, 255, 0.72), 0 16px 30px rgba(59, 47, 47, 0.12)",
    _before: {
      content: "''",
      position: "absolute",
      top: "0",
      bottom: "0",
      left: "-0.26rem",
      w: "0.52rem",
      bg: "radial-gradient(circle at 0.26rem 0.42rem, transparent 0.23rem, rgba(255, 247, 237, 0.96) 0.24rem) 0 0 / 0.52rem 0.84rem repeat-y",
    },
  }),
  ticketMain: css({
    position: "relative",
    display: "grid",
    alignContent: "center",
    px: { base: "4", sm: "7", md: "9" },
    py: { base: "3", sm: "4" },
    minW: "0",
  }),
  ticketHeader: css({
    display: "grid",
    gridTemplateColumns: "auto minmax(0, 1fr)",
    alignItems: "center",
    gap: { base: "2", md: "3" },
  }),
  ticketPlane: css({
    transform: "rotate(-24deg)",
  }),
  ticketLabel: css({
    minW: "0",
    color: "rgba(161, 112, 41, 0.86)",
    fontFamily: "Georgia, 'Times New Roman', serif",
    fontSize: { base: "0.55rem", sm: "0.72rem", md: "0.82rem" },
    fontWeight: "700",
    letterSpacing: "0",
    overflow: "hidden",
    textAlign: "center",
    textOverflow: "ellipsis",
    textTransform: "uppercase",
    whiteSpace: "nowrap",
  }),
  ticketRule: css({
    display: "grid",
    gridTemplateColumns: "1fr auto 1fr",
    alignItems: "center",
    gap: "2",
    color: "rgba(232, 93, 117, 0.58)",
    mt: { base: "0", sm: "1" },
    "& > span": {
      h: "1px",
      bg: "rgba(161, 112, 41, 0.42)",
    },
  }),
  ticketTitle: css({
    color: "rgba(161, 112, 41, 0.9)",
    fontFamily: "'Satisfy', 'Brush Script MT', 'Segoe Script', cursive",
    fontSize: { base: "2rem", sm: "2.85rem", md: "3.6rem" },
    lineHeight: "1",
    letterSpacing: "0",
    textAlign: "center",
    textShadow: "0 1px 0 rgba(255, 247, 237, 0.85)",
    whiteSpace: "nowrap",
  }),
  ticketMeta: css({
    display: "grid",
    gridTemplateColumns: "1fr 0.82fr 0.58fr",
    gap: { base: "1", sm: "3" },
    mt: { base: "2", sm: "3" },
    m: "0",
    "& > div": {
      minW: "0",
      px: { base: "0.5", md: "2" },
      borderLeftWidth: "1px",
      borderLeftStyle: "solid",
      borderLeftColor: "rgba(232, 93, 117, 0.2)",
      _first: {
        borderLeftWidth: "0",
      },
    },
    "& dt": {
      color: "rgba(232, 93, 117, 0.58)",
      fontSize: { base: "0.38rem", sm: "0.54rem", md: "0.62rem" },
      fontWeight: "800",
      lineHeight: "1.1",
      textTransform: "uppercase",
    },
    "& dd": {
      m: "0",
      mt: "1",
      color: "rgba(161, 112, 41, 0.9)",
      fontFamily: "Georgia, 'Times New Roman', serif",
      fontSize: { base: "0.42rem", sm: "0.62rem", md: "0.72rem" },
      lineHeight: "1.1",
      overflow: "hidden",
      textOverflow: "ellipsis",
      whiteSpace: "nowrap",
    },
  }),
  ticketStub: css({
    display: "grid",
    alignContent: "center",
    justifyItems: "center",
    gap: { base: "2", md: "4" },
    px: { base: "2", md: "4" },
    borderLeftWidth: "1px",
    borderLeftStyle: "dashed",
    borderLeftColor: "rgba(161, 112, 41, 0.36)",
  }),
  stubIcon: css({
    position: "relative",
    display: "grid",
    color: "rgba(161, 112, 41, 0.78)",
    "& svg:last-child": {
      position: "absolute",
      right: "-0.42rem",
      bottom: "-0.2rem",
      fill: "rgba(255, 247, 237, 0.9)",
    },
  }),
  barcode: css({
    w: { base: "1.9rem", md: "2.5rem" },
    h: { base: "3.1rem", md: "4.2rem" },
    bg: "repeating-linear-gradient(90deg, rgba(232, 93, 117, 0.5) 0 2px, transparent 2px 5px, rgba(232, 93, 117, 0.32) 5px 7px, transparent 7px 10px)",
  }),
};
