import { css } from "@styled-system/css";

export const styles = {
  controls: css({
    position: "relative",
    zIndex: "3",
    display: "grid",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    alignItems: "center",
    gap: "3",
    px: { base: "4", md: "8" },
    pt: "2",
    pb: { base: "4", md: "6" },
    bg: "linear-gradient(180deg, rgba(255, 247, 237, 0), rgba(255, 247, 237, 0.82) 42%, rgba(255, 247, 237, 0.95))",
  }),
  navButton: css({
    display: "inline-flex",
    w: { base: "3.35rem", sm: "3.8rem" },
    h: { base: "3.35rem", sm: "3.8rem" },
    alignItems: "center",
    justifyContent: "center",
    justifySelf: "start",
    p: "0",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "rgba(59, 47, 47, 0.1)",
    borderRadius: "999px",
    color: "rgba(59, 47, 47, 0.76)",
    bg: "rgba(255, 247, 237, 0.88)",
    boxShadow: "0 10px 24px rgba(59, 47, 47, 0.14)",
    cursor: "pointer",
    transition:
      "transform 160ms ease, border-color 160ms ease, background 160ms ease, color 160ms ease",
    _hover: {
      transform: "translateY(-1px)",
      borderColor: "rose",
      bg: "rgba(250, 218, 221, 0.82)",
      color: "ink",
    },
    _focusVisible: {
      outline: "3px solid rgba(59, 47, 47, 0.86)",
      outlineOffset: "3px",
    },
    _active: {
      transform: "translateY(0)",
    },
    _disabled: {
      cursor: "not-allowed",
      opacity: "0.45",
      transform: "none",
    },
  }),
  nextButton: css({
    display: "inline-flex",
    w: { base: "3.75rem", sm: "4.25rem" },
    h: { base: "3.75rem", sm: "4.25rem" },
    alignItems: "center",
    justifyContent: "center",
    justifySelf: "end",
    p: "0",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "rgba(232, 93, 117, 0.42)",
    borderRadius: "999px",
    color: "cream",
    bg: "coral",
    boxShadow: "0 12px 26px rgba(232, 93, 117, 0.34)",
    cursor: "pointer",
    transition:
      "transform 160ms ease, border-color 160ms ease, background 160ms ease, color 160ms ease",
    _hover: {
      transform: "translateY(-1px)",
      borderColor: "rose",
      bg: "rose",
    },
    _focusVisible: {
      outline: "3px solid rgba(59, 47, 47, 0.86)",
      outlineOffset: "3px",
    },
    _active: {
      transform: "translateY(0)",
    },
  }),
  replayArea: css({
    gridColumn: "2",
    minW: "0",
  }),
  replayButton: css({
    display: "inline-flex",
    minH: "3rem",
    w: "100%",
    alignItems: "center",
    justifyContent: "center",
    gap: "2",
    px: "3",
    py: "2.5",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "ink",
    borderRadius: "8px",
    color: "cream",
    bg: "ink",
    boxShadow: "0 12px 28px rgba(59, 47, 47, 0.2)",
    fontSize: "0.9rem",
    fontWeight: "850",
    cursor: "pointer",
    transition:
      "transform 160ms ease, border-color 160ms ease, background 160ms ease, color 160ms ease",
    _hover: {
      bg: "coral",
      color: "ink",
      borderColor: "coral",
      transform: "translateY(-1px)",
    },
    _focusVisible: {
      outline: "3px solid rgba(59, 47, 47, 0.86)",
      outlineOffset: "3px",
    },
    _active: {
      transform: "translateY(0)",
    },
  }),
};
