import { css } from "@styled-system/css";

export const styles = {
  photoFrame: css({
    position: "relative",
    width: "min(100%, 44rem)",
    h: "100%",
    minH: "0",
    justifySelf: "center",
    display: "grid",
    overflow: "hidden",
    p: { base: "4", sm: "5" },
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "rgba(255, 247, 237, 0.5)",
    borderRadius: { base: "18px", sm: "24px" },
    bg: "rgba(59, 47, 47, 0.08)",
    boxShadow: "0 10px 22px rgba(59, 47, 47, 0.12)",
  }),
  photoImage: css({
    position: "absolute",
    inset: "0",
    w: "100%",
    h: "100%",
    objectFit: "cover",
  }),
  photoShade: css({
    position: "absolute",
    inset: "0",
    background:
      "linear-gradient(180deg, rgba(59, 47, 47, 0.16), rgba(59, 47, 47, 0.22) 34%, rgba(59, 47, 47, 0.82))",
  }),
  photoCaption: css({
    position: "relative",
    alignSelf: "end",
    justifySelf: "center",
    width: "min(100%, 38rem)",
    display: "grid",
    gap: "3",
    p: { base: "5", sm: "7" },
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "rgba(255, 247, 237, 0.36)",
    borderRadius: { base: "18px", sm: "24px" },
    color: "cream",
    bg: "rgba(44, 34, 32, 0.58)",
    backdropFilter: "blur(18px) saturate(1.08)",
    boxShadow: "0 24px 58px rgba(0, 0, 0, 0.24)",
  }),
  photoCaptionTop: css({
    alignSelf: "start",
  }),
  captionTitle: css({
    m: "0",
    color: "cream",
    fontSize: { base: "1.85rem", sm: "2.75rem", md: "3.45rem" },
    fontWeight: "900",
    lineHeight: "1.02",
    letterSpacing: "0",
    textShadow: "0 2px 18px rgba(0, 0, 0, 0.22)",
  }),
  captionText: css({
    position: "relative",
    m: "0",
    pt: "4",
    color: "rgba(255, 247, 237, 0.9)",
    fontSize: { base: "1.06rem", sm: "1.28rem" },
    lineHeight: "1.5",
    _before: {
      content: "''",
      position: "absolute",
      top: "0",
      left: "0",
      right: "0",
      h: "1px",
      bg: "linear-gradient(90deg, rgba(255, 247, 237, 0), rgba(255, 247, 237, 0.28), rgba(255, 247, 237, 0))",
    },
  }),
  slideTitle: css({
    m: "0",
    fontSize: { base: "2rem", sm: "2.6rem" },
    fontWeight: "850",
    lineHeight: "1",
    letterSpacing: "0",
  }),
  passportPage: css({
    alignSelf: "center",
    justifySelf: "center",
    width: "min(100%, 32rem)",
    display: "grid",
    gap: "5",
    p: { base: "5", sm: "7" },
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "rgba(59, 47, 47, 0.14)",
    borderRadius: "8px",
    bg: "rgba(255, 247, 237, 0.9)",
    boxShadow: "0 22px 52px rgba(59, 47, 47, 0.14)",
  }),
  passportStamp: css({
    display: "inline-flex",
    w: "fit-content",
    alignItems: "center",
    gap: "2",
    px: "3",
    py: "1.5",
    borderWidth: "1px",
    borderStyle: "dashed",
    borderColor: "coral",
    borderRadius: "8px",
    color: "coral",
    fontSize: "0.76rem",
    fontWeight: "850",
    textTransform: "uppercase",
    letterSpacing: "0",
  }),
  messageBody: css({
    m: "0",
    color: "rgba(59, 47, 47, 0.82)",
    fontSize: "1.1rem",
    lineHeight: "1.75",
  }),
  collageLayout: css({
    alignSelf: "center",
    justifySelf: "center",
    width: "min(100%, 38rem)",
    display: "grid",
    gap: "5",
  }),
  collageGrid: css({
    display: "grid",
    gridTemplateColumns: "repeat(6, minmax(0, 1fr))",
    gridAutoRows: "minmax(6.75rem, 18svh)",
    gap: "2",
  }),
  collageItem: css({
    position: "relative",
    overflow: "hidden",
    gridColumn: "span 2",
    gridRow: "span 1",
    borderWidth: "2px",
    borderStyle: "solid",
    borderColor: "cream",
    borderRadius: "8px",
    boxShadow: "0 14px 32px rgba(59, 47, 47, 0.14)",
    _first: {
      gridColumn: "span 4",
      gridRow: "span 2",
    },
  }),
  collageImage: css({
    w: "100%",
    h: "100%",
    objectFit: "cover",
  }),
  collageCaption: css({
    display: "grid",
    gap: "3",
    p: { base: "5", sm: "7" },
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "rgba(255, 247, 237, 0.36)",
    borderRadius: { base: "24px", sm: "30px" },
    color: "cream",
    bg: "rgba(44, 34, 32, 0.66)",
    backdropFilter: "blur(18px) saturate(1.08)",
    boxShadow: "0 24px 58px rgba(59, 47, 47, 0.18)",
  }),
  collageCaptionTop: css({
    order: "-1",
  }),
};
