import { css } from "@styled-system/css";

export const styles = {
  photoFrame: css({
    position: "relative",
    width: "min(100%, 44rem)",
    h: "100%",
    minH: "0",
    justifySelf: "center",
    display: "grid",
    overflow: "hidden",
    p: { base: "4", sm: "5" },
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "creamAlpha.50",
    borderRadius: { base: "18px", sm: "24px" },
    bg: "inkAlpha.08",
    boxShadow: `0 10px 22px var(--colors-ink-alpha-12)`,
  }),
  photoImage: css({
    position: "absolute",
    inset: "0",
    w: "100%",
    h: "100%",
    objectFit: "cover",
  }),
  photoShade: css({
    position: "absolute",
    inset: "0",
    background: `linear-gradient(180deg, var(--colors-ink-alpha-24), var(--colors-ink-alpha-05) 34%, var(--colors-ink-alpha-08) 58%, var(--colors-ink-alpha-24))`,
  }),
  photoCaption: css({
    position: "relative",
    isolation: "isolate",
    alignSelf: "end",
    justifySelf: "center",
    width: "min(100%, 38rem)",
    display: "grid",
    gap: "2.5",
    p: { base: "4", sm: "5" },
    pl: { base: "5", sm: "6" },
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "goldAlpha.30",
    borderRadius: "8px",
    color: "ink",
    bg: `linear-gradient(135deg, var(--colors-cream-alpha-95), var(--colors-blush-alpha-80))`,
    backdropFilter: "blur(14px) saturate(1.08)",
    boxShadow: `0 18px 42px var(--colors-ink-alpha-18), inset 0 1px 0 var(--colors-white-alpha-70)`,
    _before: {
      content: "''",
      position: "absolute",
      top: "0",
      bottom: "0",
      left: "0",
      zIndex: "-1",
      w: "0.42rem",
      borderTopLeftRadius: "8px",
      borderBottomLeftRadius: "8px",
      bg: `linear-gradient(180deg, var(--colors-coral), var(--colors-rose) 48%, var(--colors-gold))`,
    },
    _after: {
      content: "''",
      position: "absolute",
      display: { base: "none", sm: "block" },
      top: "0.85rem",
      right: "0.85rem",
      w: "2.35rem",
      h: "2.35rem",
      borderWidth: "1px",
      borderStyle: "dashed",
      borderColor: "roseAlpha.32",
      borderRadius: "full",
      opacity: "0.72",
      pointerEvents: "none",
    },
  }),
  photoCaptionTop: css({
    alignSelf: "start",
  }),
  captionTitle: css({
    m: "0",
    maxW: "min(100%, 28rem)",
    color: "rose",
    fontFamily: "'Satisfy', 'Brush Script MT', 'Segoe Script', cursive",
    fontSize: { base: "2.15rem", sm: "2.8rem", md: "3.25rem" },
    fontWeight: "400",
    lineHeight: "1.08",
    letterSpacing: "0",
    textShadow: `0 1px 0 var(--colors-cream)`,
  }),
  captionText: css({
    position: "relative",
    m: "0",
    maxW: "32rem",
    pt: "3",
    color: "inkAlpha.86",
    fontSize: { base: "1rem", sm: "1.12rem" },
    fontWeight: "650",
    lineHeight: "1.46",
    _before: {
      content: "''",
      position: "absolute",
      top: "0",
      left: "0",
      w: "min(7.5rem, 45%)",
      h: "2px",
      bg: `linear-gradient(90deg, var(--colors-gold), var(--colors-coral), var(--colors-rose-alpha-18))`,
    },
  }),
  captionTextSolo: css({
    pt: "0",
    color: "ink",
    fontSize: { base: "1.06rem", sm: "1.18rem" },
    _before: {
      display: "none",
    },
  }),
  videoLayout: css({
    alignSelf: "stretch",
    justifySelf: "center",
    width: "min(100%, 44rem)",
    h: "100%",
    minH: "0",
    display: "grid",
    gridTemplateRows: "minmax(0, 1fr) auto",
    gap: "4",
  }),
  videoLayoutCaptionTop: css({
    gridTemplateRows: "auto minmax(0, 1fr)",
  }),
  videoFrame: css({
    position: "relative",
    minH: "0",
    overflow: "hidden",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "creamAlpha.50",
    borderRadius: { base: "18px", sm: "24px" },
    bg: "inkDeep",
    boxShadow: `0 10px 22px var(--colors-ink-alpha-12)`,
  }),
  videoPlayer: css({
    display: "block",
    w: "100%",
    h: "100%",
    objectFit: "contain",
    bg: "inkDeep",
  }),
  videoCaption: css({
    position: "relative",
    isolation: "isolate",
    display: "grid",
    gap: "2.5",
    p: { base: "4", sm: "5" },
    pl: { base: "5", sm: "6" },
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "goldAlpha.30",
    borderRadius: "8px",
    color: "ink",
    bg: `linear-gradient(135deg, var(--colors-cream-alpha-95), var(--colors-blush-alpha-80))`,
    backdropFilter: "blur(14px) saturate(1.08)",
    boxShadow: `0 18px 42px var(--colors-ink-alpha-14), inset 0 1px 0 var(--colors-white-alpha-70)`,
    _before: {
      content: "''",
      position: "absolute",
      top: "0",
      bottom: "0",
      left: "0",
      zIndex: "-1",
      w: "0.42rem",
      borderTopLeftRadius: "8px",
      borderBottomLeftRadius: "8px",
      bg: `linear-gradient(180deg, var(--colors-coral), var(--colors-rose) 48%, var(--colors-gold))`,
    },
    _after: {
      content: "''",
      position: "absolute",
      display: { base: "none", sm: "block" },
      top: "0.85rem",
      right: "0.85rem",
      w: "2.35rem",
      h: "2.35rem",
      borderWidth: "1px",
      borderStyle: "dashed",
      borderColor: "roseAlpha.32",
      borderRadius: "full",
      opacity: "0.72",
      pointerEvents: "none",
    },
  }),
  videoCaptionTop: css({
    order: "-1",
  }),
  slideTitle: css({
    m: "0",
    fontSize: { base: "2rem", sm: "2.6rem" },
    fontWeight: "850",
    lineHeight: "1",
    letterSpacing: "0",
  }),
  passportPage: css({
    alignSelf: "center",
    justifySelf: "center",
    width: "min(100%, 32rem)",
    display: "grid",
    gap: "5",
    p: { base: "5", sm: "7" },
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "inkAlpha.14",
    borderRadius: "8px",
    bg: "creamAlpha.90",
    boxShadow: `0 22px 52px var(--colors-ink-alpha-14)`,
  }),
  passportStamp: css({
    display: "inline-flex",
    w: "fit-content",
    alignItems: "center",
    gap: "2",
    px: "3",
    py: "1.5",
    borderWidth: "1px",
    borderStyle: "dashed",
    borderColor: "coral",
    borderRadius: "8px",
    color: "coral",
    fontSize: "0.76rem",
    fontWeight: "850",
    textTransform: "uppercase",
    letterSpacing: "0",
  }),
  messageBody: css({
    m: "0",
    color: "inkAlpha.80",
    fontSize: "1.1rem",
    lineHeight: "1.75",
  }),
  collageLayout: css({
    alignSelf: "stretch",
    justifySelf: "center",
    width: "min(100%, 38rem)",
    h: "100%",
    minH: "0",
    display: "grid",
    gridTemplateRows: "minmax(0, 1fr) auto",
    gap: "5",
  }),
  collageLayoutCaptionTop: css({
    gridTemplateRows: "auto minmax(0, 1fr)",
  }),
  collageGrid: css({
    display: "grid",
    h: "100%",
    minH: "0",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    gridTemplateRows: "repeat(2, minmax(0, 1fr))",
    gap: "2",
  }),
  collageGridTwo: css({
    gridTemplateColumns: "1fr",
    gridTemplateRows: "repeat(2, minmax(0, 1fr))",
  }),
  collageGridThree: css({
    gridTemplateRows: "1.6fr 1fr",
  }),
  collageGridFour: css({
    gridTemplateRows: "repeat(2, minmax(0, 1fr))",
  }),
  collageGridFive: css({
    gridTemplateRows: "1.45fr repeat(2, minmax(0, 1fr))",
  }),
  collageGridMany: css({
    gridTemplateRows: "repeat(3, minmax(0, 1fr))",
  }),
  collageItem: css({
    position: "relative",
    overflow: "hidden",
    gridColumn: "span 1",
    gridRow: "span 1",
    borderWidth: "2px",
    borderStyle: "solid",
    borderColor: "cream",
    borderRadius: "8px",
    boxShadow: `0 14px 32px var(--colors-ink-alpha-14)`,
  }),
  collageItemFeatured: css({
    gridColumn: "1 / -1",
  }),
  collageImage: css({
    w: "100%",
    h: "100%",
    objectFit: "cover",
  }),
  collageCaption: css({
    position: "relative",
    isolation: "isolate",
    display: "grid",
    gap: "2.5",
    p: { base: "4", sm: "5" },
    pl: { base: "5", sm: "6" },
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "goldAlpha.30",
    borderRadius: "8px",
    color: "ink",
    bg: `linear-gradient(135deg, var(--colors-cream-alpha-95), var(--colors-blush-alpha-80))`,
    backdropFilter: "blur(14px) saturate(1.08)",
    boxShadow: `0 18px 42px var(--colors-ink-alpha-14), inset 0 1px 0 var(--colors-white-alpha-70)`,
    _before: {
      content: "''",
      position: "absolute",
      top: "0",
      bottom: "0",
      left: "0",
      zIndex: "-1",
      w: "0.42rem",
      borderTopLeftRadius: "8px",
      borderBottomLeftRadius: "8px",
      bg: `linear-gradient(180deg, var(--colors-coral), var(--colors-rose) 48%, var(--colors-gold))`,
    },
    _after: {
      content: "''",
      position: "absolute",
      display: { base: "none", sm: "block" },
      top: "0.85rem",
      right: "0.85rem",
      w: "2.35rem",
      h: "2.35rem",
      borderWidth: "1px",
      borderStyle: "dashed",
      borderColor: "roseAlpha.32",
      borderRadius: "full",
      opacity: "0.72",
      pointerEvents: "none",
    },
  }),
  collageCaptionTop: css({
    order: "-1",
  }),
};
