import { css } from "@styled-system/css";

export const styles = {
  photoFrame: css({
    position: "relative",
    width: "min(100%, 44rem)",
    h: "100%",
    minH: "0",
    justifySelf: "center",
    display: "grid",
    overflow: "hidden",
    p: { base: "4", sm: "5" },
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "creamAlpha.50",
    borderRadius: { base: "18px", sm: "24px" },
    bg: "inkAlpha.08",
    boxShadow: `0 10px 22px var(--colors-ink-alpha-12)`,
  }),
  photoImage: css({
    position: "absolute",
    inset: "0",
    w: "100%",
    h: "100%",
    objectFit: "cover",
  }),
  photoShade: css({
    position: "absolute",
    inset: "0",
    background: `linear-gradient(180deg, var(--colors-ink-alpha-24), var(--colors-ink-alpha-05) 34%, var(--colors-ink-alpha-08) 58%, var(--colors-ink-alpha-24))`,
  }),
  photoCaption: css({
    position: "relative",
    isolation: "isolate",
    alignSelf: "end",
    justifySelf: "center",
    width: "min(100%, 38rem)",
    display: "grid",
    gap: "2.5",
    p: { base: "4", sm: "5" },
    pl: { base: "5", sm: "6" },
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "goldAlpha.30",
    borderRadius: "8px",
    color: "ink",
    bg: `linear-gradient(135deg, var(--colors-cream-alpha-95), var(--colors-blush-alpha-80))`,
    backdropFilter: "blur(14px) saturate(1.08)",
    boxShadow: `0 18px 42px var(--colors-ink-alpha-18), inset 0 1px 0 var(--colors-white-alpha-70)`,
    _before: {
      content: "''",
      position: "absolute",
      top: "0",
      bottom: "0",
      left: "0",
      zIndex: "-1",
      w: "0.42rem",
      borderTopLeftRadius: "8px",
      borderBottomLeftRadius: "8px",
      bg: `linear-gradient(180deg, var(--colors-coral), var(--colors-rose) 48%, var(--colors-gold))`,
    },
    _after: {
      content: "''",
      position: "absolute",
      display: { base: "none", sm: "block" },
      top: "0.85rem",
      right: "0.85rem",
      w: "2.35rem",
      h: "2.35rem",
      borderWidth: "1px",
      borderStyle: "dashed",
      borderColor: "roseAlpha.32",
      borderRadius: "full",
      opacity: "0.72",
      pointerEvents: "none",
    },
  }),
  photoCaptionTop: css({
    alignSelf: "start",
  }),
  captionTitle: css({
    m: "0",
    maxW: "min(100%, 28rem)",
    color: "rose",
    fontFamily: "'Satisfy', 'Brush Script MT', 'Segoe Script', cursive",
    fontSize: { base: "2.15rem", sm: "2.8rem", md: "3.25rem" },
    fontWeight: "400",
    lineHeight: "1.08",
    letterSpacing: "0",
    textShadow: `0 1px 0 var(--colors-cream)`,
  }),
  captionText: css({
    position: "relative",
    m: "0",
    maxW: "32rem",
    pt: "3",
    color: "inkAlpha.86",
    fontSize: { base: "1rem", sm: "1.12rem" },
    fontWeight: "650",
    lineHeight: "1.46",
    _before: {
      content: "''",
      position: "absolute",
      top: "0",
      left: "0",
      w: "min(7.5rem, 45%)",
      h: "2px",
      bg: `linear-gradient(90deg, var(--colors-gold), var(--colors-coral), var(--colors-rose-alpha-18))`,
    },
  }),
  captionTextSolo: css({
    pt: "0",
    color: "ink",
    fontSize: { base: "1.06rem", sm: "1.18rem" },
    _before: {
      display: "none",
    },
  }),
  videoLayout: css({
    alignSelf: "stretch",
    justifySelf: "center",
    width: "min(100%, 44rem)",
    h: "100%",
    minH: "0",
    display: "grid",
    gridTemplateRows: "minmax(0, 1fr) auto",
    gap: "4",
  }),
  videoLayoutCaptionTop: css({
    gridTemplateRows: "auto minmax(0, 1fr)",
  }),
  videoFrame: css({
    position: "relative",
    minH: "0",
    overflow: "hidden",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "creamAlpha.50",
    borderRadius: { base: "18px", sm: "24px" },
    bg: "inkDeep",
    boxShadow: `0 10px 22px var(--colors-ink-alpha-12)`,
  }),
  videoPlayer: css({
    display: "block",
    w: "100%",
    h: "100%",
    objectFit: "contain",
    bg: "inkDeep",
  }),
  videoCaption: css({
    position: "relative",
    isolation: "isolate",
    display: "grid",
    gap: "2.5",
    p: { base: "4", sm: "5" },
    pl: { base: "5", sm: "6" },
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "goldAlpha.30",
    borderRadius: "8px",
    color: "ink",
    bg: `linear-gradient(135deg, var(--colors-cream-alpha-95), var(--colors-blush-alpha-80))`,
    backdropFilter: "blur(14px) saturate(1.08)",
    boxShadow: `0 18px 42px var(--colors-ink-alpha-14), inset 0 1px 0 var(--colors-white-alpha-70)`,
    _before: {
      content: "''",
      position: "absolute",
      top: "0",
      bottom: "0",
      left: "0",
      zIndex: "-1",
      w: "0.42rem",
      borderTopLeftRadius: "8px",
      borderBottomLeftRadius: "8px",
      bg: `linear-gradient(180deg, var(--colors-coral), var(--colors-rose) 48%, var(--colors-gold))`,
    },
    _after: {
      content: "''",
      position: "absolute",
      display: { base: "none", sm: "block" },
      top: "0.85rem",
      right: "0.85rem",
      w: "2.35rem",
      h: "2.35rem",
      borderWidth: "1px",
      borderStyle: "dashed",
      borderColor: "roseAlpha.32",
      borderRadius: "full",
      opacity: "0.72",
      pointerEvents: "none",
    },
  }),
  videoCaptionTop: css({
    order: "-1",
  }),
  postcard: css({
    position: "relative",
    isolation: "isolate",
    alignSelf: "center",
    justifySelf: "center",
    width: "min(100%, 36rem)",
    minH: { base: "min(68svh, 27rem)", sm: "25rem" },
    display: "grid",
    p: { base: "5", sm: "7" },
    overflow: "hidden",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "goldAlpha.30",
    borderRadius: "8px",
    color: "ink",
    bg: "creamSoft",
    boxShadow: `0 24px 54px var(--colors-ink-alpha-16), inset 0 0 0 1px var(--colors-white-alpha-70)`,
    transform: "rotate(-1.15deg)",
    _before: {
      content: "''",
      position: "absolute",
      inset: "0",
      zIndex: "-2",
      background: `radial-gradient(circle at 1rem 1rem, var(--colors-gold-alpha-12) 0 1px, transparent 1.5px) 0 0 / 1.2rem 1.2rem, linear-gradient(135deg, var(--colors-cream-soft), var(--colors-cream) 58%, var(--colors-blush-alpha-50))`,
    },
    _after: {
      content: "''",
      position: "absolute",
      inset: { base: "0.48rem", sm: "0.64rem" },
      zIndex: "-1",
      borderWidth: "1px",
      borderStyle: "dashed",
      borderColor: "goldAlpha.30",
      borderRadius: "6px",
      pointerEvents: "none",
    },
  }),
  postageStamp: css({
    position: "absolute",
    top: { base: "5.1rem", sm: "5.85rem" },
    right: { base: "5", sm: "7" },
    zIndex: "1",
    display: "grid",
    placeItems: "center",
    w: { base: "4.15rem", sm: "4.85rem" },
    h: { base: "3.65rem", sm: "4.3rem" },
    borderWidth: "1px",
    borderStyle: "dashed",
    borderColor: "roseAlpha.50",
    borderRadius: "6px",
    color: "rose",
    bg: `linear-gradient(135deg, var(--colors-blush-alpha-80), var(--colors-cream-alpha-95))`,
    boxShadow: `inset 0 0 0 4px var(--colors-cream-alpha-50), 0 8px 18px var(--colors-ink-alpha-08)`,
    transform: "rotate(4deg)",
    _before: {
      content: "''",
      position: "absolute",
      inset: "0.42rem",
      borderWidth: "1px",
      borderStyle: "solid",
      borderColor: "creamAlpha.80",
      borderRadius: "4px",
    },
    "& svg": {
      position: "relative",
    },
  }),
  postcardContent: css({
    display: "grid",
    gridTemplateColumns: {
      base: "minmax(0, 1fr) minmax(5.4rem, 34%)",
      sm: "minmax(0, 1fr) 10.5rem",
    },
    gap: { base: "3", sm: "6" },
    minH: "0",
  }),
  postcardMessage: css({
    position: "relative",
    isolation: "isolate",
    display: "grid",
    alignContent: "center",
    gap: { base: "4", sm: "5" },
    minW: "0",
    pr: { base: "2", sm: "3" },
    _before: {
      content: "''",
      position: "absolute",
      inset: { base: "4.5rem 0 0", sm: "5rem 0 0" },
      zIndex: "-1",
      opacity: "0.72",
      background: `repeating-linear-gradient(to bottom, transparent 0, transparent 2.15rem, var(--colors-gold-alpha-12) 2.15rem, var(--colors-gold-alpha-12) calc(2.15rem + 1px))`,
    },
  }),
  postcardLabel: css({
    display: "inline-flex",
    w: "fit-content",
    alignItems: "center",
    gap: "2",
    px: "3",
    py: "1.5",
    borderWidth: "1px",
    borderStyle: "dashed",
    borderColor: "coral",
    borderRadius: "8px",
    color: "coral",
    fontSize: "0.76rem",
    fontWeight: "850",
    textTransform: "uppercase",
    letterSpacing: "0",
  }),
  slideTitle: css({
    m: "0",
    maxW: "16ch",
    color: "rose",
    fontFamily: "Georgia, 'Times New Roman', serif",
    fontSize: { base: "1.7rem", sm: "2.35rem" },
    fontWeight: "750",
    lineHeight: "1.05",
    letterSpacing: "0",
    overflowWrap: "anywhere",
    textShadow: `0 1px 0 var(--colors-cream)`,
  }),
  messageBody: css({
    m: "0",
    maxW: "24rem",
    color: "inkAlpha.86",
    fontSize: { base: "1.02rem", sm: "1.12rem" },
    fontWeight: "500",
    lineHeight: "1.62",
    overflowWrap: "anywhere",
  }),
  postcardAddress: css({
    display: "grid",
    alignContent: "center",
    gap: { base: "4", sm: "5" },
    minW: "0",
    pl: { base: "3", sm: "5" },
    borderLeftWidth: "1px",
    borderLeftStyle: "solid",
    borderLeftColor: "goldAlpha.30",
    "& span": {
      display: "block",
      h: "1px",
      w: "100%",
      bg: "roseAlpha.32",
    },
    "& span:nth-of-type(1)": {
      w: "82%",
    },
    "& span:nth-of-type(3)": {
      w: "72%",
    },
  }),
  stampedNote: css({
    position: "relative",
    isolation: "isolate",
    alignSelf: "center",
    justifySelf: "center",
    width: "min(100%, 31rem)",
    minH: { base: "min(58svh, 23rem)", sm: "22rem" },
    display: "grid",
    alignContent: "center",
    justifyItems: "center",
    gap: { base: "4", sm: "5" },
    p: { base: "6", sm: "8" },
    overflow: "hidden",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "goldAlpha.30",
    borderRadius: "8px",
    color: "ink",
    textAlign: "center",
    bg: "creamAlpha.95",
    boxShadow: `0 22px 52px var(--colors-ink-alpha-14), inset 0 0 0 1px var(--colors-white-alpha-70)`,
    transform: "rotate(0.65deg)",
    _before: {
      content: "''",
      position: "absolute",
      inset: "0",
      zIndex: "-2",
      background: `radial-gradient(circle at 1rem 1rem, var(--colors-gold-alpha-12) 0 1px, transparent 1.5px) 0 0 / 1.35rem 1.35rem, linear-gradient(145deg, var(--colors-cream-alpha-95), var(--colors-cream-soft) 58%, var(--colors-blush-alpha-50))`,
    },
    _after: {
      content: "''",
      position: "absolute",
      inset: { base: "0.5rem", sm: "0.7rem" },
      zIndex: "-1",
      borderWidth: "1px",
      borderStyle: "dashed",
      borderColor: "goldAlpha.30",
      borderRadius: "6px",
      pointerEvents: "none",
    },
  }),
  stampedNoteFinal: css({
    width: "min(100%, 33rem)",
    transform: "rotate(-0.45deg)",
    _before: {
      background: `radial-gradient(circle at 1rem 1rem, var(--colors-rose-alpha-12) 0 1px, transparent 1.5px) 0 0 / 1.35rem 1.35rem, linear-gradient(145deg, var(--colors-cream-soft), var(--colors-blush-alpha-50) 54%, var(--colors-sky-muted-alpha-35))`,
    },
  }),
  stampedNoteMark: css({
    position: "absolute",
    top: { base: "1.45rem", sm: "1.2rem" },
    right: { base: "-2.25rem", sm: "-1.4rem" },
    zIndex: "-1",
    w: { base: "9.5rem", sm: "11rem" },
    h: { base: "9.5rem", sm: "11rem" },
    borderWidth: "2px",
    borderStyle: "dashed",
    borderColor: "roseAlpha.18",
    borderRadius: "full",
    color: "roseAlpha.18",
    opacity: "0.9",
    transform: "rotate(10deg)",
    pointerEvents: "none",
    "& span:first-child": {
      position: "absolute",
      inset: "1rem",
      borderWidth: "1px",
      borderStyle: "solid",
      borderColor: "currentColor",
      borderRadius: "full",
    },
    "& span:last-child": {
      position: "absolute",
      top: "50%",
      left: "18%",
      w: "64%",
      h: "2px",
      bg: "currentColor",
      borderRadius: "full",
    },
  }),
  stampedNoteLabel: css({
    display: "inline-flex",
    w: "fit-content",
    alignItems: "center",
    gap: "2",
    px: "3",
    py: "1.5",
    borderWidth: "1px",
    borderStyle: "dashed",
    borderColor: "coral",
    borderRadius: "8px",
    color: "coral",
    fontSize: "0.76rem",
    fontWeight: "850",
    textTransform: "uppercase",
    letterSpacing: "0",
  }),
  noteTitle: css({
    m: "0",
    maxW: "15ch",
    color: "rose",
    fontFamily: "Georgia, 'Times New Roman', serif",
    fontSize: { base: "1.95rem", sm: "2.55rem" },
    fontWeight: "760",
    lineHeight: "1.05",
    letterSpacing: "0",
    overflowWrap: "anywhere",
    textShadow: `0 1px 0 var(--colors-cream)`,
  }),
  noteBody: css({
    m: "0",
    maxW: "26rem",
    color: "inkAlpha.86",
    fontSize: { base: "1.04rem", sm: "1.15rem" },
    fontWeight: "500",
    lineHeight: "1.68",
    overflowWrap: "anywhere",
  }),
  collageLayout: css({
    alignSelf: "stretch",
    justifySelf: "center",
    width: "min(100%, 38rem)",
    h: "100%",
    minH: "0",
    display: "grid",
    gridTemplateRows: "minmax(0, 1fr) auto",
    gap: "5",
  }),
  collageLayoutCaptionTop: css({
    gridTemplateRows: "auto minmax(0, 1fr)",
  }),
  collageGrid: css({
    display: "grid",
    h: "100%",
    minH: "0",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    gridTemplateRows: "repeat(2, minmax(0, 1fr))",
    gap: "2",
  }),
  collageGridTwo: css({
    gridTemplateColumns: "1fr",
    gridTemplateRows: "repeat(2, minmax(0, 1fr))",
  }),
  collageGridThree: css({
    gridTemplateRows: "1.6fr 1fr",
  }),
  collageGridFour: css({
    gridTemplateRows: "repeat(2, minmax(0, 1fr))",
  }),
  collageGridFive: css({
    gridTemplateRows: "1.45fr repeat(2, minmax(0, 1fr))",
  }),
  collageGridMany: css({
    gridTemplateRows: "repeat(3, minmax(0, 1fr))",
  }),
  collageItem: css({
    position: "relative",
    overflow: "hidden",
    gridColumn: "span 1",
    gridRow: "span 1",
    borderWidth: "2px",
    borderStyle: "solid",
    borderColor: "cream",
    borderRadius: "8px",
    boxShadow: `0 14px 32px var(--colors-ink-alpha-14)`,
  }),
  collageItemFeatured: css({
    gridColumn: "1 / -1",
  }),
  collageImage: css({
    w: "100%",
    h: "100%",
    objectFit: "cover",
  }),
  collageCaption: css({
    position: "relative",
    isolation: "isolate",
    display: "grid",
    gap: "2.5",
    p: { base: "4", sm: "5" },
    pl: { base: "5", sm: "6" },
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "goldAlpha.30",
    borderRadius: "8px",
    color: "ink",
    bg: `linear-gradient(135deg, var(--colors-cream-alpha-95), var(--colors-blush-alpha-80))`,
    backdropFilter: "blur(14px) saturate(1.08)",
    boxShadow: `0 18px 42px var(--colors-ink-alpha-14), inset 0 1px 0 var(--colors-white-alpha-70)`,
    _before: {
      content: "''",
      position: "absolute",
      top: "0",
      bottom: "0",
      left: "0",
      zIndex: "-1",
      w: "0.42rem",
      borderTopLeftRadius: "8px",
      borderBottomLeftRadius: "8px",
      bg: `linear-gradient(180deg, var(--colors-coral), var(--colors-rose) 48%, var(--colors-gold))`,
    },
    _after: {
      content: "''",
      position: "absolute",
      display: { base: "none", sm: "block" },
      top: "0.85rem",
      right: "0.85rem",
      w: "2.35rem",
      h: "2.35rem",
      borderWidth: "1px",
      borderStyle: "dashed",
      borderColor: "roseAlpha.32",
      borderRadius: "full",
      opacity: "0.72",
      pointerEvents: "none",
    },
  }),
  collageCaptionTop: css({
    order: "-1",
  }),
};
