import { css } from "@styled-system/css";

export const styles = {
  progressArea: css({
    position: "relative",
    zIndex: "3",
    px: { base: "4", md: "8" },
    pt: { base: "4", md: "6" },
    pb: "2",
  }),
  progressMeta: css({
    display: "grid",
    gridTemplateColumns: "auto minmax(3.5rem, 1fr) auto",
    alignItems: "center",
    gap: "3",
    fontSize: "0.78rem",
    fontWeight: "800",
    color: "rgba(59, 47, 47, 0.74)",
  }),
  progressLabel: css({
    display: "inline-flex",
    alignItems: "center",
    gap: "1.5",
    textTransform: "uppercase",
    letterSpacing: "0",
  }),
  progressActions: css({
    display: "inline-flex",
    minW: "0",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: "2",
    whiteSpace: "nowrap",
  }),
  musicButton: css({
    display: "inline-flex",
    w: "2.25rem",
    h: "2.25rem",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: "0",
    p: "0",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "rgba(59, 47, 47, 0.18)",
    borderRadius: "999px",
    color: "ink",
    bg: "rgba(255, 247, 237, 0.78)",
    boxShadow: "0 8px 18px rgba(59, 47, 47, 0.1)",
    cursor: "pointer",
    transition: "transform 160ms ease, border-color 160ms ease, background 160ms ease",
    _hover: {
      transform: "translateY(-1px)",
      borderColor: "rose",
      bg: "rgba(250, 218, 221, 0.82)",
    },
    _focusVisible: {
      outline: "3px solid rgba(59, 47, 47, 0.86)",
      outlineOffset: "3px",
    },
    _active: {
      transform: "translateY(0)",
    },
  }),
  progressTrack: css({
    position: "relative",
    minW: "0",
    h: "0.42rem",
    borderRadius: "999px",
    bg: "rgba(59, 47, 47, 0.1)",
  }),
  progressFill: css({
    h: "100%",
    borderRadius: "999px",
    bg: "rose",
    transition: "width 220ms ease",
  }),
  progressPlaneBadge: css({
    position: "absolute",
    top: "50%",
    zIndex: "1",
    w: "2rem",
    h: "2rem",
    display: "grid",
    placeItems: "center",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "rgba(59, 47, 47, 0.12)",
    borderRadius: "full",
    color: "ink",
    bg: "rgba(255, 247, 237, 0.92)",
    boxShadow: "0 8px 18px rgba(59, 47, 47, 0.16)",
    pointerEvents: "none",
    transform: "translate(-50%, -50%)",
    transition: "left 220ms ease",
  }),
  progressPlane: css({
    display: "block",
    w: "1.15rem",
    h: "1.02rem",
  }),
};
