import { css } from "@styled-system/css";

export const styles = {
  progressArea: css({
    position: "relative",
    zIndex: "3",
    px: { base: "4", md: "8" },
    pt: { base: "4", md: "6" },
    pb: "2",
  }),
  progressMeta: css({
    display: "grid",
    gridTemplateColumns: "auto minmax(3.5rem, 1fr) auto",
    alignItems: "center",
    gap: { base: "2", sm: "3" },
    fontSize: "0.78rem",
    fontWeight: "800",
    color: "inkAlpha.80",
  }),
  progressStatus: css({
    display: "inline-flex",
    minH: "2.25rem",
    alignItems: "center",
    gap: "2",
    px: "3",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "inkAlpha.10",
    borderRadius: "999px",
    color: "inkAlpha.80",
    bg: "creamAlpha.90",
    boxShadow: `0 4px 10px var(--colors-ink-alpha-06)`,
    letterSpacing: "0",
    whiteSpace: "nowrap",
  }),
  progressActions: css({
    display: "inline-flex",
    minW: "0",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: "2",
    whiteSpace: "nowrap",
  }),
  progressTrack: css({
    position: "relative",
    minW: "0",
    h: "0.42rem",
    borderRadius: "999px",
    bg: "inkAlpha.10",
  }),
  progressFill: css({
    h: "100%",
    borderRadius: "999px",
    bg: "rose",
    transition: "width 220ms ease",
  }),
  progressPlaneBadge: css({
    position: "absolute",
    top: "50%",
    zIndex: "1",
    w: "2rem",
    h: "2rem",
    display: "grid",
    placeItems: "center",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "inkAlpha.12",
    borderRadius: "full",
    color: "ink",
    bg: "creamAlpha.90",
    boxShadow: `0 8px 18px var(--colors-ink-alpha-16)`,
    pointerEvents: "none",
    transform: "translate(-50%, -50%)",
    transition: "left 220ms ease",
  }),
  progressPlane: css({
    display: "block",
    w: "1.15rem",
    h: "1.02rem",
  }),
};
