import { css } from "@styled-system/css";

export const styles = {
  introScreen: css({
    minH: "100svh",
    display: "grid",
    alignItems: "center",
    px: { base: "5", md: "8" },
    py: { base: "6", md: "8" },
  }),
  introContent: css({
    width: "100%",
    minW: "0",
    maxW: { base: "min(32rem, calc(100vw - 2.5rem))", md: "46rem" },
    mx: "auto",
    display: "grid",
    gap: { base: "5", sm: "6", md: "7" },
  }),
  introTitle: css({
    m: "0",
    display: "grid",
    gap: "0.06em",
    justifyItems: "center",
    color: "coral",
    fontFamily: "'Satisfy', 'Brush Script MT', 'Segoe Script', cursive",
    fontSize: { base: "4.35rem", sm: "5.9rem", md: "7rem" },
    fontWeight: "400",
    lineHeight: "1.1",
    letterSpacing: "0",
    textAlign: "center",
    textShadow: "0 2px 0 rgba(255, 247, 237, 0.78)",
  }),
  introTitleLine: css({
    display: "block",
    w: "fit-content",
    _first: {
      fontSize: "0.78em",
    },
    _last: {
      display: "inline-flex",
      alignItems: "center",
      gap: "2",
      fontSize: "0.84em",
    },
  }),
  introTitleCake: css({
    display: "inline-block",
    flexShrink: "0",
    fontFamily: "system-ui, 'Apple Color Emoji', 'Segoe UI Emoji', sans-serif",
    fontSize: "0.52em",
    lineHeight: "1",
    transform: "translateY(0.12em)",
  }),
  introBody: css({
    m: "0",
    maxW: "40rem",
    color: "rgba(59, 47, 47, 0.82)",
    fontSize: { base: "1.05rem", md: "1.15rem" },
    lineHeight: "1.65",
    textAlign: "center",
  }),
  choicePanel: css({
    display: "grid",
    minW: "0",
    gap: { base: "3", md: "4" },
  }),
  musicChoicePanel: css({
    display: "grid",
    minW: "0",
    gap: { base: "4", md: "5" },
    p: { base: "4", sm: "5" },
    borderWidth: "1.5px",
    borderStyle: "dashed",
    borderColor: "rgba(232, 93, 117, 0.32)",
    borderRadius: { base: "1.5rem", sm: "1.85rem" },
    color: "ink",
    bg: "rgba(255, 247, 237, 0.5)",
    boxShadow: "inset 0 1px 0 rgba(255, 255, 255, 0.68), 0 8px 18px rgba(59, 47, 47, 0.05)",
  }),
  musicPrompt: css({
    m: "0",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "3",
    color: "rose",
    fontSize: { base: "1.08rem", md: "1.22rem" },
    fontWeight: "800",
    lineHeight: "1.2",
    textAlign: "center",
  }),
  choiceGrid: css({
    display: "grid",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    gap: { base: "3", sm: "4" },
  }),
};
