import { css } from "@styled-system/css";

export const styles = {
  introScreen: css({
    minH: "100svh",
    display: "grid",
    alignItems: "center",
    px: { base: "5", md: "8" },
    py: { base: "6", md: "8" },
  }),
  introContent: css({
    width: "100%",
    minW: "0",
    maxW: { base: "min(32rem, calc(100vw - 2.5rem))", md: "46rem" },
    mx: "auto",
    display: "grid",
    gap: { base: "5", sm: "6", md: "7" },
  }),
  introTitle: css({
    m: "0",
    display: "grid",
    gap: "0.06em",
    justifyItems: "center",
    color: "coral",
    fontFamily: "'Satisfy', 'Brush Script MT', 'Segoe Script', cursive",
    fontSize: { base: "4.35rem", sm: "5.9rem", md: "7rem" },
    fontWeight: "400",
    lineHeight: "1.1",
    letterSpacing: "0",
    textAlign: "center",
    textShadow: "0 2px 0 rgba(255, 247, 237, 0.78)",
  }),
  introTitleLine: css({
    display: "block",
    w: "fit-content",
    _first: {
      fontSize: "0.78em",
    },
    _last: {
      display: "inline-flex",
      alignItems: "center",
      gap: "2",
      fontSize: "0.84em",
    },
  }),
  introTitleCake: css({
    display: "inline-block",
    flexShrink: "0",
    fontFamily: "system-ui, 'Apple Color Emoji', 'Segoe UI Emoji', sans-serif",
    fontSize: "0.52em",
    lineHeight: "1",
    transform: "translateY(0.12em)",
  }),
  introBody: css({
    m: "0",
    maxW: "40rem",
    color: "rgba(59, 47, 47, 0.82)",
    fontSize: { base: "1.05rem", md: "1.15rem" },
    lineHeight: "1.65",
    textAlign: "center",
  }),
  choicePanel: css({
    display: "grid",
    minW: "0",
    gap: { base: "3", md: "4" },
  }),
  musicChoicePanel: css({
    display: "grid",
    minW: "0",
    gap: { base: "4", md: "5" },
    p: { base: "4", sm: "5" },
    borderWidth: "1.5px",
    borderStyle: "dashed",
    borderColor: "rgba(232, 93, 117, 0.32)",
    borderRadius: { base: "1.5rem", sm: "1.85rem" },
    color: "ink",
    bg: "rgba(255, 247, 237, 0.5)",
    boxShadow: "inset 0 1px 0 rgba(255, 255, 255, 0.68), 0 8px 18px rgba(59, 47, 47, 0.05)",
  }),
  musicPrompt: css({
    m: "0",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "3",
    color: "rose",
    fontSize: { base: "1.08rem", md: "1.22rem" },
    fontWeight: "800",
    lineHeight: "1.2",
    textAlign: "center",
  }),
  choiceGrid: css({
    display: "grid",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    gap: { base: "3", sm: "4" },
  }),
  choiceButton: css({
    display: "inline-flex",
    minH: { base: "3.45rem", sm: "3.75rem" },
    alignItems: "center",
    justifyContent: "center",
    gap: "2.5",
    px: { base: "4", sm: "5" },
    py: "3",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "rgba(59, 47, 47, 0.12)",
    borderRadius: "999px",
    color: "ink",
    bg: "rgba(255, 251, 245, 0.86)",
    boxShadow: "0 4px 10px rgba(59, 47, 47, 0.08), inset 0 1px 0 rgba(255, 255, 255, 0.74)",
    fontSize: { base: "1rem", md: "1.08rem" },
    fontWeight: "800",
    lineHeight: "1.2",
    cursor: "pointer",
    userSelect: "none",
    transition:
      "transform 160ms ease, border-color 160ms ease, background 160ms ease, box-shadow 160ms ease",
    _hover: {
      transform: "translateY(-1px)",
      borderColor: "rgba(232, 93, 117, 0.34)",
    },
    _focusVisible: {
      outline: "3px solid rgba(59, 47, 47, 0.86)",
      outlineOffset: "3px",
    },
    _active: {
      transform: "translateY(0)",
    },
  }),
  choiceButtonSelected: css({
    borderColor: "rgba(232, 93, 117, 0.55)",
    bg: "linear-gradient(180deg, #F86F66 0%, #EA5F59 100%)",
    color: "cream",
    boxShadow: "0 8px 16px rgba(232, 93, 117, 0.14), inset 0 1px 0 rgba(255, 255, 255, 0.28)",
  }),
  primaryButton: css({
    display: "inline-flex",
    minH: { base: "4rem", sm: "4.35rem" },
    w: "100%",
    alignItems: "center",
    justifyContent: "center",
    gap: "2",
    px: { base: "5", sm: "6" },
    py: "3",
    border: "0",
    borderRadius: "999px",
    color: "cream",
    bg: "linear-gradient(180deg, #F86F66 0%, #EA5F59 100%)",
    boxShadow: "0 8px 16px rgba(232, 93, 117, 0.14), 0 1px 0 rgba(59, 47, 47, 0.06)",
    fontSize: { base: "1.12rem", md: "1.26rem" },
    fontWeight: "850",
    lineHeight: "1.2",
    cursor: "pointer",
    userSelect: "none",
    transition: "transform 160ms ease, opacity 160ms ease, background 160ms ease",
    _hover: {
      transform: "translateY(-1px)",
      bg: "linear-gradient(180deg, #FF766B 0%, #EE625E 100%)",
    },
    _focusVisible: {
      outline: "3px solid rgba(59, 47, 47, 0.86)",
      outlineOffset: "3px",
    },
    _active: {
      transform: "translateY(0)",
    },
    _disabled: {
      cursor: "not-allowed",
      opacity: "0.48",
      transform: "none",
    },
  }),
};
