import { css } from "@styled-system/css";

export const styles = {
  introScreen: css({
    minH: "100svh",
    display: "grid",
    alignItems: "center",
    px: { base: "5", md: "8" },
    py: "8",
  }),
  introContent: css({
    width: "100%",
    maxW: "32rem",
    mx: "auto",
    display: "grid",
    gap: "7",
  }),
  introMark: css({
    display: "inline-flex",
    w: "fit-content",
    alignItems: "center",
    gap: "2",
    px: "3",
    py: "1.5",
    borderWidth: "1px",
    borderStyle: "dashed",
    borderColor: "rose",
    borderRadius: "8px",
    color: "rose",
    bg: "rgba(255, 247, 237, 0.7)",
    fontSize: "0.78rem",
    fontWeight: "800",
    letterSpacing: "0",
    textTransform: "uppercase",
  }),
  introTitle: css({
    m: "0",
    maxW: "12ch",
    fontSize: { base: "3rem", sm: "3.7rem" },
    fontWeight: "850",
    lineHeight: "0.96",
    letterSpacing: "0",
  }),
  introBody: css({
    m: "0",
    maxW: "29rem",
    color: "rgba(59, 47, 47, 0.82)",
    fontSize: "1.05rem",
    lineHeight: "1.7",
  }),
  choicePanel: css({
    display: "grid",
    gap: "4",
  }),
  musicPrompt: css({
    m: "0",
    fontSize: "0.95rem",
    fontWeight: "800",
  }),
  choiceGrid: css({
    display: "grid",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    gap: "3",
  }),
  choiceButton: css({
    display: "inline-flex",
    minH: "3.25rem",
    alignItems: "center",
    justifyContent: "center",
    gap: "2",
    px: "3",
    py: "3",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "rgba(59, 47, 47, 0.22)",
    borderRadius: "8px",
    color: "ink",
    bg: "rgba(255, 247, 237, 0.7)",
    boxShadow: "0 10px 24px rgba(59, 47, 47, 0.08)",
    fontSize: "0.95rem",
    fontWeight: "800",
    lineHeight: "1.2",
    cursor: "pointer",
    transition: "transform 160ms ease, border-color 160ms ease, background 160ms ease",
    _hover: {
      transform: "translateY(-1px)",
      borderColor: "rose",
    },
    _focusVisible: {
      outline: "3px solid rgba(59, 47, 47, 0.86)",
      outlineOffset: "3px",
    },
    _active: {
      transform: "translateY(0)",
    },
  }),
  choiceButtonSelected: css({
    borderColor: "rose",
    bg: "blush",
    color: "ink",
  }),
  primaryButton: css({
    display: "inline-flex",
    minH: "3.4rem",
    w: "100%",
    alignItems: "center",
    justifyContent: "center",
    gap: "2",
    px: "5",
    py: "3",
    border: "0",
    borderRadius: "8px",
    color: "cream",
    bg: "ink",
    boxShadow: "0 16px 34px rgba(59, 47, 47, 0.22)",
    fontSize: "1rem",
    fontWeight: "850",
    lineHeight: "1.2",
    cursor: "pointer",
    transition: "transform 160ms ease, opacity 160ms ease, background 160ms ease",
    _hover: {
      transform: "translateY(-1px)",
      bg: "coral",
      color: "ink",
    },
    _focusVisible: {
      outline: "3px solid rgba(59, 47, 47, 0.86)",
      outlineOffset: "3px",
    },
    _active: {
      transform: "translateY(0)",
    },
    _disabled: {
      cursor: "not-allowed",
      opacity: "0.48",
      transform: "none",
    },
  }),
};
